services:
  broker-service:
    build:
      context: ./../broker_service
      dockerfile: ./../broker_service/broker-service.dockerfile
    restart: always
    ports:
      - "1700:1700"
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    build:
      context: ./../auth_service
      dockerfile: ./../auth_service/auth-service.dockerfile
    restart: always
    ports:
      - "1800:1800"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: go_microservice_auth_service
    depends_on:
      - postgres

  logger-service:
    build:
      context: ./../logger_service
      dockerfile: ./../logger_service/logger-service.dockerfile
    restart: always
    ports:
      - "1900:1900"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - mongo
  
  mailer-service:
    build:
      context: ./../mailer_service
      dockerfile: ./../mailer_service/mailer-service.dockerfile
    restart: always
    ports:
      - "2000:2000"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: none
      MAIL_FROMNAME: "Venukishore R"
      MAIL_FROM_ADDRESS: venuvk0304@gmail.com

  listener-service:
    build:
      context: ./../listener_service
      dockerfile: ./../listener_service/listener-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
  
  front-end:
    build:
      context: ./../front-end
      dockerfile: ./../front-end/front-end.dockerfile
    restart: always
    ports:
      - "1600:1600"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - BROKER_URL=http://go_microservice_broker

  postgres:
    image: 'postgres:14'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: go_microservice_auth_service
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data

  
  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=logs
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./db-data/mongo/:/data/db 

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"

  rabbitmq:
    image: 'rabbitmq:3.13-alpine'
    ports:
      - "5672:5672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/
  
  adminer:
    image: 'adminer:4.8.1'
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - mongo